import sgMail from "@sendgrid/mail";

const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY || "";
const FROM_EMAIL = process.env.FROM_EMAIL || "";
const TO_EMAIL = process.env.TO_EMAIL || "";
const SLACK_WEBHOOK_URL = process.env.SLACK_WEBHOOK_URL || "";

sgMail.setApiKey(SENDGRID_API_KEY);

interface ErrorAlert {
  service: string;
  route: string;
  error: string;
  severity: string;
  file?: string;
  line?: number;
  jira_key?: string;
  github_pr_url?: string;
  dashboard_url?: string;
}

// Send Email Alert
export async function sendEmailAlert(alert: ErrorAlert) {
  console.log("=== EMAIL DEBUG ===");
  console.log("API Key exists:", !!SENDGRID_API_KEY);
  console.log("From:", FROM_EMAIL);
  console.log("To:", TO_EMAIL);
  console.log("==================");
  try {
    if (!SENDGRID_API_KEY || !FROM_EMAIL || !TO_EMAIL) {
      console.log("SendGrid not configured — skipping email");
      return;
    }

    const severityEmoji =
      alert.severity === "critical"
        ? "🔴"
        : alert.severity === "high"
          ? "🟠"
          : alert.severity === "medium"
            ? "🟡"
            : "🟢";

    const msg = {
      to: TO_EMAIL,
      from: FROM_EMAIL,
      subject: `${severityEmoji} [DevMind] ${alert.severity?.toUpperCase()} error in ${alert.service}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: #1a1a2e; padding: 20px; border-radius: 8px;">
            <h1 style="color: #4ade80; margin: 0;">🤖 DevMind Alert</h1>
          </div>
          
          <div style="padding: 20px; background: #f9f9f9; border-radius: 8px; margin-top: 10px;">
            <h2 style="color: #ef4444;">${severityEmoji} ${alert.severity?.toUpperCase()} Error Detected</h2>
            
            <table style="width: 100%; border-collapse: collapse;">
              <tr>
                <td style="padding: 8px; font-weight: bold; color: #666;">Service:</td>
                <td style="padding: 8px;">${alert.service} → ${alert.route}</td>
              </tr>
              <tr style="background: #f0f0f0;">
                <td style="padding: 8px; font-weight: bold; color: #666;">Error:</td>
                <td style="padding: 8px; font-family: monospace; color: #ef4444;">${alert.error}</td>
              </tr>
              ${
                alert.file
                  ? `
              <tr>
                <td style="padding: 8px; font-weight: bold; color: #666;">Location:</td>
                <td style="padding: 8px; font-family: monospace;">${alert.file} line ${alert.line}</td>
              </tr>`
                  : ""
              }
              ${
                alert.jira_key
                  ? `
              <tr style="background: #f0f0f0;">
                <td style="padding: 8px; font-weight: bold; color: #666;">Jira:</td>
                <td style="padding: 8px;">${alert.jira_key}</td>
              </tr>`
                  : ""
              }
            </table>

            <div style="margin-top: 20px; display: flex; gap: 10px;">
              ${
                alert.github_pr_url
                  ? `
              <a href="${alert.github_pr_url}" 
                 style="background: #7c3aed; color: white; padding: 10px 20px; 
                        border-radius: 6px; text-decoration: none; margin-right: 10px;">
                🔀 View GitHub PR
              </a>`
                  : ""
              }
              <a href="${alert.dashboard_url || "http://localhost:3002"}" 
                 style="background: #2563eb; color: white; padding: 10px 20px; 
                        border-radius: 6px; text-decoration: none;">
                📊 View Dashboard
              </a>
            </div>

            <p style="color: #999; font-size: 12px; margin-top: 20px;">
              This alert was automatically generated by DevMind — Autonomous AI Debugging Platform
            </p>
          </div>
        </div>
      `,
    };

    await sgMail.send(msg);
    console.log(`✅ Email alert sent to ${TO_EMAIL}`);
  } catch (err: any) {
    console.error("Email alert failed:", err.message);
  }
}

// Send Slack Alert
export async function sendSlackAlert(alert: ErrorAlert) {
  try {
    if (!SLACK_WEBHOOK_URL) {
      console.log("Slack not configured — skipping");
      return;
    }

    console.log("Sending Slack alert to:", SLACK_WEBHOOK_URL.substring(0, 40));

    const payload = {
      text: `🚨 *DevMind Alert* — ${alert.severity?.toUpperCase()} Error`,
      attachments: [
        {
          color:
            alert.severity === "critical"
              ? "#ff0000"
              : alert.severity === "high"
                ? "#ff6600"
                : alert.severity === "medium"
                  ? "#ffcc00"
                  : "#00cc00",
          fields: [
            { title: "Service", value: alert.service, short: true },
            { title: "Route", value: alert.route, short: true },
            { title: "Error", value: alert.error, short: false },
            {
              title: "File",
              value: alert.file
                ? `${alert.file} line ${alert.line}`
                : "Unknown",
              short: true,
            },
            {
              title: "Jira",
              value: alert.jira_key || "Not created",
              short: true,
            },
          ],
          actions: [
            {
              type: "button",
              text: "📊 View Dashboard",
              url: alert.dashboard_url || "http://localhost:3002",
            },
          ],
        },
      ],
    };

    const response = await fetch(SLACK_WEBHOOK_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    const text = await response.text();
    console.log("Slack response:", text);

    if (text === "ok") {
      console.log("✅ Slack alert sent!");
    }
  } catch (err: any) {
    console.error("Slack alert failed:", err.message);
  }
}

// Send both alerts
export async function sendAlerts(alert: ErrorAlert) {
  await Promise.all([sendEmailAlert(alert), sendSlackAlert(alert)]);
}
